# Generated by Django 5.0 on 2024-05-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-id']},
        ),
    ]
