# Generated by Django 5.0 on 2024-05-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment_alter_album_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='logo',
            field=models.FileField(default=1, upload_to='logo'),
            preserve_default=False,
        ),
    ]
