# Generated by Django 5.0 on 2024-05-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_personaldetail_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
