# Generated by Django 5.0 on 2024-05-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_personaldetail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='buttonName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
