# Generated by Django 5.0 on 2024-05-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_appointment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone',
        ),
    ]
