# Generated by Django 5.0 on 2024-05-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='testimonialimage')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='icon',
            field=models.FileField(default=1, upload_to='clientIconimage'),
            preserve_default=False,
        ),
    ]
