# Generated by Django 5.0 on 2024-05-27 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_album_image_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallerys', to='app.gallery'),
        ),
    ]
