# Generated by Django 5.0 on 2024-05-27 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_album_album_remove_gallery_title_album_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='app.album'),
        ),
    ]
