# Generated by Django 5.0 on 2024-05-27 09:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_gallery_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='companydescriptionimage')),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
