# Generated by Django 5.0 on 2024-05-27 10:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_companydescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herobanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='herobannerimage')),
                ('smallImage', models.ImageField(upload_to='smallImage')),
                ('subDescription', models.CharField(max_length=400)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
