# Generated by Django 5.0 on 2024-05-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_herobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='companyName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
