# Generated by Django 5.0 on 2024-05-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_herobanner_completedproject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobanner',
            name='completedProject',
        ),
        migrations.RemoveField(
            model_name='herobanner',
            name='satisfiedClient',
        ),
        migrations.AddField(
            model_name='about',
            name='completedProject',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='satisfiedClient',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
