# Generated by Django 5.0 on 2024-05-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_album_image_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=1, upload_to='galleryimage'),
            preserve_default=False,
        ),
    ]
