# Generated by Django 5.0 on 2024-05-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(default=1, upload_to='Albumimage'),
            preserve_default=False,
        ),
    ]
