# Generated by Django 5.0 on 2024-05-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FileField(upload_to='Albumimage'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(upload_to='galleryimage'),
        ),
    ]
