# Generated by Django 5.0 on 2024-05-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
