# Generated by Django 5.0 on 2024-05-29 08:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_contact_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
