# Generated by Django 5.0 on 2024-05-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_herobanner_smallimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='whatsappUrl',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
