# Generated by Django 5.0 on 2024-05-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_personaldetail_whatsappurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='subdescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
