# Generated by Django 5.0 on 2024-05-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_about_subdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='subdescription',
            field=models.CharField(max_length=400),
        ),
    ]
