# Generated by Django 5.0 on 2024-05-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_about_subdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='mapUrl',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
