# Generated by Django 5.0 on 2024-05-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_personaldetail_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='linkedinUrl',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
